"""create inicial tables

Revision ID: ef94cd7d3d7f
Revises: 
Create Date: 2025-05-25 20:54:35.861017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef94cd7d3d7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=11), nullable=True),
    sa.Column('lastname', sa.String(length=11), nullable=True),
    sa.Column('dateofbirth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_client_id'), 'table_client', ['id'], unique=False)
    op.create_table('table_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_product_id'), 'table_product', ['id'], unique=False)
    op.create_table('table_seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=11), nullable=True),
    sa.Column('lastname', sa.String(length=11), nullable=True),
    sa.Column('dateofbirth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_seller_id'), 'table_seller', ['id'], unique=False)
    op.create_table('table_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateofBuy', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['table_client.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['table_seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_sale_id'), 'table_sale', ['id'], unique=False)
    op.create_table('table_sell_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['table_product.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['table_sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_sell_product_id'), 'table_sell_product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_sell_product_id'), table_name='table_sell_product')
    op.drop_table('table_sell_product')
    op.drop_index(op.f('ix_table_sale_id'), table_name='table_sale')
    op.drop_table('table_sale')
    op.drop_index(op.f('ix_table_seller_id'), table_name='table_seller')
    op.drop_table('table_seller')
    op.drop_index(op.f('ix_table_product_id'), table_name='table_product')
    op.drop_table('table_product')
    op.drop_index(op.f('ix_table_client_id'), table_name='table_client')
    op.drop_table('table_client')
    # ### end Alembic commands ###
